Website/Polls/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'Polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view()  , name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Website/Profile/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^', views.index, name='index'),
]

Website/Website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^profile/', include("Profile.urls")),
    url(r'^polls/', include("Polls.urls")),
    #path('polls/', include('Polls.urls')),
]

Website/Polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return  now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

Website/Profile/models.py
from django.db import models

# Create your models here.

Website/Polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question
from django.utils import timezone


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:20]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'Polls/index.html', context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'Polls/detail.html', {'question': question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'Polls/results.html', {'question': question})

class IndexView(generic.ListView):
    template_name = 'Polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name= 'Polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'Polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'Polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('Polls:results', args=(question.id,)))

Website/Profile/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "Profile/index.html")

Website/Polls/templates/Polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Polls</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'Polls\css\bootstrap.min.css' %}" type="text/css">
    <script src="{% static 'Polls\js\jquery.3.5.0.min.js' %}"></script>
    <script src="{% static 'Polls\js\popper.min.js' %}"></script>
    <script src="{% static 'Polls\js\bootstrap.min.js' %} "></script>

    <style>
        footer {
           position: relative;
           left: 0;
           bottom: 0;
           width: 100%;
        }
        </style>
</head>
    <body>
        <!-- Start Header or Navigation -->
        <section id="navigation">
            <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">
                        <h2 class="text-white"><small>Polls</small></h2>
                    </a>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-end align-items-center" id=navbarContent>
                        <ul class="navbar-nav">
                            <li class="nav-item"><a class="nav-link active" href="#">Home</a></li>
                            <li class="nav-item"><a class="nav-link active" href="#">About</a></li>
                            <li class="nav-item"><a class="nav-link active" href="#">Admin</a></li>
                            <li class="nav-item"><a class="nav-link active" href="#">Management</a></li>
                            <li class="nav-item"><a class="nav-link active" href="#">HOD</a></li>
                            <li class="nav-item"><a class="nav-link active" href="#">Teacher</a></li>
                            <li class="nav-item"><a class="nav-link active" href="#">Student</a></li>
                            <li class="nav-item"><a class="nav-link active" href="#">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
        </section>
        <!-- End of Header or Navigation -->
        <div class="align-items-center">
        {% block content %}
        {% endblock %}
        </div>
        <!-- Start of Footer -->
        
        <footer class="container-fluid bg-primary">
            
            <div class="row">
                <div class="col-sm-2">
                    <h4 class="text-white"><small>SOCIAL LINKS</small></h4>
                    <table class="table">
                        <tr><td><a href="https://www.facebook.com"><div class="text-white">Facebook</div></a></td></tr>
                        <tr><td><a href="https://www.instagram.com"><div class="text-white">Instagram</div></a></td></tr>
                        <tr><td><a href="https://www.google.com"><div class="text-white">Google</div></a></td></tr>
                        <tr><td><a href="https://www.twitter.com"><div class="text-white">Twitter</div></a></td></tr>
                        <tr><td><a href="https://www.youtube.com"><div class="text-white">Youtube</div></a></td></tr>
                    </table>
                </div>
            

                <div class="col-sm-1"></div>

                <div class="col-sm-2">
                    <h4 class="text-white"><small>PROJECT LINKS</small></h4>
                    <table class="table">
                        <tr><td><a href="#"><div class="text-white">Home</div></a></td></tr>
                        <tr><td><a href="#"><div class="text-white">About</div></a></td></tr>
                        <tr><td><a href="#"><div class="text-white">Email</div></a></td></tr>
                        <tr><td><a href="#"><div class="text-white">Contact</div></a></td></tr>
                        <tr><td><a href="#"><div class="text-white">Developers</div></a></td></tr>
                    </table>
                </div>
               

                <div class="col-sm-1"></div>

                <div class="col-sm-2">
                    <h4 class="text-white"><small>PROJECT LINKS</small></h4>
                    <table class="table">
                        <tr><td><a href="#"><div class="text-white">Admin</div></a></td></tr>
                        <tr><td><a href="#"><div class="text-white">Management</div></a></td></tr>
                        <tr><td><a href="#"><div class="text-white">HOD</div></a></td></tr>
                        <tr><td><a href="#"><div class="text-white">Teacher</div></a></td></tr>
                        <tr><td><a href="#"><div class="text-white">Student</div></a></td></tr>
                    </table>
                </div>
                
                <div class="col-sm-1"></div>

                <div class="col-sm-3">
                    <h4 class="text-white"><small>CONTACT US</small></h4>
                    <p class="text-white">Harold GM Institute of Technology<br>
                        South Triangle, Quezon City <br>
                        Phone: +63 906 219 4539 <br>
                        E-mail: haroldmamitag@gmail.com <br>
                        Website: www.twinspika.webs.com
                    </p>
                </div>

            </div>
            <h4 class="badge badge-info">© Copyright: Harold Mamitag Reserved<small></small></h4>

        </footer>
    

        <!-- End of Footer   -->
      


        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    </body>

</html>

Website/Polls/templates/Polls/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Polls</title>
  </head>
  <body>

    {% extends "Polls/base2.html" %}

    {% block content %}

    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'Polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
    {% endblock %}
    


  </body>
</html>

Website/Polls/templates/Polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Polls</title>
  </head>
  <body>
    {% extends "Polls/base2.html" %}

    {% block content %}
        {% if latest_question_list %}

        {% for question in latest_question_list %}
            <p class="lead font-weight-bold" ><a href="{% url 'Polls:detail' question.id %}">{{ question.question_text }}</a></p>
        {% endfor %}

        {% else %}
            <p class="lead font-weight-bold">No polls are available.</p>
        {% endif %}
    {% endblock %}


  </body>
</html>

Website/Polls/templates/Polls/results.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Polls</title>
  </head>
  <body>
    {% extends "Polls/base2.html" %}

    {% block content %}

    <h1>{{ question.question_text }}</h1>


    {% for choice in question.choice_set.all %}
        <p class="lead font-weight-bold">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p>
    {% endfor %}

    <p> <a href="{% url 'Polls:detail' question.id %}">Vote again?</a> <br>
        <a href="{% url 'Polls:index' %}">Back to Questions</a>

    </p>


    {% endblock %}


  </body>
</html>

Website/Profile/templates/Profile/base.html
<h1>Hello from base</h1>

Website/Profile/templates/Profile/index.html
<h1>Hello from index</h1>